### ISSUE TITLE
Bug: Timelines Not Being Added or Changed

### ISSUE THREAD

**Issue by che-wf** [tillberg/timeline#1]
I've been looking for something like this for a while. If someone didn't make it, I was going to make something similar for myself. So, thanks!

The problem that I'm having is that I cloned the repo. I've made some changes to the folder with timeline data. I've added some new files. So, currently, there should be no example data left. However, it's still showing data from one of the old files. Is there a place that I'm supposed to declare where I am adding my data? Thanks!

**Comment by tillberg** [comment]
Is it maybe possible that you have a maybe-hidden backup file of one of the examples still in the folder you're working in? e.g. emacs drops copies of files ending in tilde by default. Those will get picked up by timeline. You could add a `console.log(filename);` just before this line to see each file as it is loaded by the server: https://github.com/tillberg/timeline/blob/9c608261228ee741e4f4660730bfa6a7c579d952/lib/serve.js#L22

(you're welcome! glad you like it!)

**Comment by che-wf** [comment]
Actually, I'm on a Windows machine. But I think the problem was that I wasn't in the folder directory when I started the server. So, it couldn't find my files. So, I got it working. Thanks!
